### ISSUE TITLE
add user entity, repo, service and controllers

### ISSUE THREAD

**Issue by xuzishuo1996** [ece651-project/backend#2]

**Comment by yifanjia** [comment]
Hi, I am playing around apartment entity and its repo. I find it sometimes neccessary to have some default atttributes of users. Sometimes I need to add a user to the user repo and only after that I may try to insert some apartments. (Because if the database is empty, an apartment can't be inserted due to the ManyToOne mapping). Now there are some magic strings used for creating a dummy user. Is it possible to define some public string literals for attributes for default user? Thank!
