### ISSUE TITLE
add apartment entity, repo, service and controllers

### ISSUE THREAD

**Issue by xuzishuo1996** [ece651-project/backend#3]

**Comment by yifanjia** [comment]
@xuzishuo1996 
Hi, with the current configuration of JacksonConfig.java, I find that the backend will return "Apartment" or "House" as the Type to the front end while the front end must gives the backend something like "APARTMENT" instead of "Apartment" (otherwise there will be a json parsing error). I suspect that the two directions (from front-end to backend and from backend to front-end) are actually using different parsing rules, which leads to the inconsistency. 

This problem seems to be solved if I commented "mapper.configure(WRITE_ENUMS_USING_TO_STRING, true);" I guess in the case, I am using the default parsing rule of Jackson and then both front end and back end can pass "APARTMENT" to each other.

We may discuss it further in the back-end group meeting later today.
